/**
 * Author:  Viaud
 * Created: 8 oct. 2016
 */
INSERT INTO CONTACT(ID,NAME,PHONE_NUMBER,ADDRESS_STREET,ADDRESS_CITY) VALUES (1,'toto','0600000000','1 rue albert','Cannes');
INSERT INTO CONTACT(ID,NAME,PHONE_NUMBER,ADDRESS_STREET,ADDRESS_CITY) VALUES (2,'tata','0600000001','2 rue albert','Avignon');
